---

vcsa_deploy_sso_password: "{{ lookup('env', 'VMWARE_PASSWORD') | default('') }}"
vcsa_deploy_sso_site_name: Default-Site
vcsa_deploy_sso_domain_name: home.ad

vcsa_deploy_network_mount_dir: /vmfs/volumes/nfs_vol01
# vcsa_iso: iso/VMware-VCSA-all-6.7.0-13010631.iso
# vcsa_iso: iso/VMware-VCSA-all-6.7.0-14836122.iso
# vcsa_iso: iso/VMware-VCSA-all-7.0.0-15952498.iso
# vcsa_iso: iso/VMware-VCSA-all-7.0.0-16189094.iso
vcsa_deploy_vcsa_iso: iso/VMware-VCSA-all-7.0.1-17491101.iso

vcsa_deploy_iso_mount_dir: /mnt/iso
vcsa_deploy_ovftool: "{{ vcsa_deploy_network_mount_dir }}/images/ovftool/lin64/ovftool"

vcsa_deploy_network_ip_scheme: static
vcsa_deploy_disk_mode: thin

vcsa_deploy_vcenter_appliance_name: vcenter
vcsa_deploy_vcenter_appliance_size: small

vcsa_deploy_target_esx_datastore: datastore1
vcsa_deploy_target_esx_portgroup: mgmt

vcsa_deploy_ssh_enable: true
vcsa_deploy_time_tools_sync: false
vcsa_deploy_net_addr_family: ipv4

vcsa_deploy_vcenter_ip_address: "{{ lookup('env', 'VMWARE_HOST') | default('') }}"
vcsa_deploy_vcenter_username: "{{ lookup('env', 'VMWARE_USER') | default('') }}"
vcsa_deploy_vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD') | default('') }}"
vcsa_deploy_vcenter_ova_file: ""
# vcenter_fqdn: "vcenter{{ vcenter_ip_address.split('.')[-1] }}.{{ sso_domain_name }}"
vcsa_deploy_vcenter_fqdn: "{{ vcsa_deploy_vcenter_ip_address }}"
vcsa_deploy_vcenter_netmask: 255.255.255.0
vcsa_deploy_vcenter_gateway: 192.168.1.254
vcsa_deploy_vcenter_net_prefix: 24

vcsa_deploy_dns_servers:
  - 8.8.4.4
vcsa_deploy_ntp_servers:
  - pool.ntp.org

vcsa_deploy_network_host: ""
vcsa_deploy_network_path: ""

vcsa_deploy_wait_for_connection_retries: 300
vcsa_deploy_wait_for_connection_delay: 5

vcsa_deploy_default_ports:
  http: 80
  https: 443
