---

vcenter_add_host_datacenter: cloud
vcenter_add_host_cluster: mylab
vcenter_add_host_appliance_name: vcenter
vcenter_add_host_target_esx_datastore: datastore1
vcenter_add_host_configure_vswitch: true
vcenter_add_host_apply_license: true
