---

vcenter_datacenter: cloud
vcenter_cluster: mylab
enable_ha: no
enable_drs: yes
enable_vsan: no

vcenter_resource_pools:
  - infra
  - management
  - manageto

vcenter_vm_folders:
  - template
  - redhat

vcenter_license: ''

vcenter_appliance_name: vcenter